//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoUrlChecker.KidsFilms.Biz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Domain
    {
        public int DomainId { get; set; }
        public int ProviderId { get; set; }
        public int DomainTypeId { get; set; }
        public string UrlBegin { get; set; }
        public string UrlEnd { get; set; }
    
        public virtual DomainType DomainType { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
