//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoUrlChecker.KidsFilms.Biz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Episode
    {
        public int EpisodeId { get; set; }
        public Nullable<int> Part { get; set; }
        public string EpisodeTitle { get; set; }
        public int FilmId { get; set; }
        public int Seconds { get; set; }
        public string Url { get; set; }
        public string PosterId { get; set; }
        public int StartTime { get; set; }
        public int EndTime { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int PlayCount { get; set; }
        public bool IsFree { get; set; }
        public bool IsActiveLink { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual Film Film { get; set; }
    }
}
