//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoUrlChecker.KidsFilms.Biz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public Film()
        {
            this.Episode = new HashSet<Episode>();
        }
    
        public int FilmId { get; set; }
        public string FilmTitle { get; set; }
        public int LanguageId { get; set; }
        public int ProviderId { get; set; }
        public int GenreId { get; set; }
        public Nullable<int> Year { get; set; }
        public string ThumbUrl { get; set; }
        public bool IsPrivate { get; set; }
    
        public virtual ICollection<Episode> Episode { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
