//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoUrlChecker.KidsFilms.Biz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genre
    {
        public Genre()
        {
            this.Film = new HashSet<Film>();
        }
    
        public int GenreId { get; set; }
        public string GenreName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Film> Film { get; set; }
    }
}
