//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoUrlChecker.KidsFilms.Biz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public Provider()
        {
            this.Domain = new HashSet<Domain>();
            this.Film = new HashSet<Film>();
        }
    
        public int ProviderId { get; set; }
        public string ProviderName { get; set; }
    
        public virtual ICollection<Domain> Domain { get; set; }
        public virtual ICollection<Film> Film { get; set; }
    }
}
